spring.application.name=mauli-vruddhashram



server.port=${PORT:8080}

razorpay.key=rzp_test_SzXIuxEkzJ9trx 
razorpay.secret=y1UqUZy@KE901Zx1GTq1Uou7

#razorpay.key=${RAZORPAY_KEY}
#razorpay.secret=${RAZORPAY_SECRET}